spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/trappd_db?useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    platform: mysql
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 100
        generate-statistics: true
        order_inserts: true
        order_updates: true
    show-sql: false
  application:
    name: trappd-data-service
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    com:
      easycompany:
        trappd: debug
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: info
      springframework:
        orm:
          jpa: info
        transaction: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    loggers:
      enabled: true
env:
  type: prod

amazonProperties:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  bucketName: trappd-covid-data-snapshots
server:
  port: 8081