INSERT into state (id,code,  name, country_code) values (1,'AP',' Andhra Pradesh', 'IN');
INSERT into state (id,code,  name, country_code) values (2,'AR',' Arunachal Pradesh', 'IN');
INSERT into state (id,code,  name, country_code) values (3,'AS',' Assam', 'IN');
INSERT into state (id,code,  name, country_code) values (4,'BR',' Bihar', 'IN');
INSERT into state (id,code,  name, country_code) values (5,'CT',' Chhattisgarh', 'IN');
INSERT into state (id,code,  name, country_code) values (6,'GA',' Goa', 'IN');
INSERT into state (id,code,  name, country_code) values (7,'GJ',' Gujarat', 'IN');
INSERT into state (id,code,  name, country_code) values (8,'HR',' Haryana', 'IN');
INSERT into state (id,code,  name, country_code) values (9,'HP',' Himachal Pradesh', 'IN');
INSERT into state (id,code,  name, country_code) values (10,'JH',' Jharkhand', 'IN');
INSERT into state (id,code,  name, country_code) values (11,'KA',' Karnataka', 'IN');
INSERT into state (id,code,  name, country_code) values (12,'KL',' Kerala', 'IN');
INSERT into state (id,code,  name, country_code) values (13,'MP',' Madhya Pradesh', 'IN');
INSERT into state (id,code,  name, country_code) values (14,'MH',' Maharashtra', 'IN');
INSERT into state (id,code,  name, country_code) values (15,'MN',' Manipur', 'IN');
INSERT into state (id,code,  name, country_code) values (16,'ML',' Meghalaya', 'IN');
INSERT into state (id,code,  name, country_code) values (17,'MZ',' Mizoram', 'IN');
INSERT into state (id,code,  name, country_code) values (18,'NL',' Nagaland', 'IN');
INSERT into state (id,code,  name, country_code) values (19,'OR',' Odisha', 'IN');
INSERT into state (id,code,  name, country_code) values (20,'PB',' Punjab', 'IN');
INSERT into state (id,code,  name, country_code) values (21,'RJ',' Rajasthan', 'IN');
INSERT into state (id,code,  name, country_code) values (22,'SK',' Sikkim', 'IN');
INSERT into state (id,code,  name, country_code) values (23,'TN',' Tamil Nadu', 'IN');
INSERT into state (id,code,  name, country_code) values (24,'TG',' Telangana', 'IN');
INSERT into state (id,code,  name, country_code) values (25,'TR',' Tripura', 'IN');
INSERT into state (id,code,  name, country_code) values (26,'UT',' Uttarakhand', 'IN');
INSERT into state (id,code,  name, country_code) values (27,'UP',' Uttar Pradesh', 'IN');
INSERT into state (id,code,  name, country_code) values (28,'WB',' West Bengal', 'IN');
INSERT into state (id,code,  name, country_code) values (29,'AN',' Andaman and Nicobar Islands', 'IN');
INSERT into state (id,code,  name, country_code) values (30,'CH',' Chandigarh', 'IN');
INSERT into state (id,code,  name, country_code) values (31,'DN',' Dadra and Nagar Haveli', 'IN');
INSERT into state (id,code,  name, country_code) values (32,'DD',' Daman and Diu', 'IN');
INSERT into state (id,code,  name, country_code) values (33,'DL',' Delhi', 'IN');
INSERT into state (id,code,  name, country_code) values (34,'JK',' Jammu and Kashmir', 'IN');
INSERT into state (id,code,  name, country_code) values (35,'LA',' Ladakh', 'IN');
INSERT into state (id,code,  name, country_code) values (36,'LD',' Lakshadweep', 'IN');
INSERT into state (id,code,  name, country_code) values (37,'PY',' Puducherry', 'IN');