spring:
  profiles:
    active: main
  datasource:
    password: ${RDS_KEY}
    url: jdbc:mysql://trappd-db-prod.cwr1iqiduzzs.ap-south-1.rds.amazonaws.com:3306/trappd_db_prod?useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    platform: mysql
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 10
        generate-statistics: true
    show-sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
  application:
    name: trappd
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    com:
      easycompany:
        trappd: debug
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: info
      springframework:
        orm:
          jpa: info
        transaction: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    loggers:
      enabled: true
env:
  type: prod

server:
  port: 8080